#ifndef PHANTOM_WRITER_VERSION_H
#define PHANTOM_WRITER_VERSION_H

#define PHANTOM_WRITER_VERSION_MAJOR 0
#define PHANTOM_WRITER_VERSION_MINOR 1
#define PHANTOM_WRITER_VERSION_PATCH 0

#define PHANTOM_WRITER_VERSION "0.1.0"

#endif // PHANTOM_WRITER_VERSION_H
